# Generated by Django 4.1.6 on 2023-02-12 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number nust be entered in the format: '+998906417999'. Up to 14 digits allowed",
                                regex="^\\+?1?\\d{9,14}$",
                            )
                        ],
                    ),
                ),
                ("first_login", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number nust be entered in the format: '+998906417999'. Up to 14 digits allowed",
                                regex="^\\+?1?\\d{9,14}$",
                            )
                        ],
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "validated",
                    models.BooleanField(
                        default=False,
                        help_text="if it is true,that means user have validate otp correctly i second API",
                    ),
                ),
            ],
        ),
    ]
