# Generated by Django 4.1.6 on 2023-02-12 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base_info", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jshshir",
                    models.CharField(
                        max_length=14,
                        verbose_name="Personal identification number of individuals",
                    ),
                ),
                (
                    "passport_series",
                    models.CharField(max_length=2, verbose_name="Passport series"),
                ),
                (
                    "passport_num",
                    models.CharField(max_length=7, verbose_name="Passport number"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="first_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last_name"),
                ),
                ("surname", models.CharField(max_length=20, verbose_name="Last_name")),
                ("birth_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizenship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.citizenship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermamentAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(max_length=100, verbose_name="Home address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.districts",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.regions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraduatedEdu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduated_date", models.DateField()),
                (
                    "doc_ser_num",
                    models.TextField(
                        max_length=20,
                        verbose_name="Document series and number of your graduated Institution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.districts",
                    ),
                ),
                (
                    "graduate_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.institutions",
                    ),
                ),
                (
                    "graduate_institution_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.institutiontype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.regions",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_info.states",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
